technitium_pfx_password: ENC[AES256_GCM,data:NKE6Uv37YjK+IN/RGw==,iv:nt2yJt5XB5CPbFP+W+bfYZByWOyfbD8i2qR007718So=,tag:RWCzXbFWqhUOqnXqaDIeoA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bDlXOEVkcXNNblE1cEkr
        OThITmpFUmpoU2hLV0wxMExDWGtIbmdRY1FjCkw5d0MyNG1sQ1RNUXhid3BaQkVv
        ZGI1ZFNEQkw1TEpDUEFEK2cxT3JxTjgKLS0tIElUbnZQTFY5YmFVeHlydDZSbklr
        TEpCVXBFWkkrSDBUK3JlbzAxTzBUcjQK9JfgNdxYHSEe/5WuEIBZjn754UPzdKr1
        vheSmBniSN/bKABMOELvfi3oBXUSe2qYbcqHZ/xe6V3FkAXwuRd7Ew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-08-14T11:56:28Z"
  mac: ENC[AES256_GCM,data:4xzQFiW7x8PYtqvtKdbz1lY3kdryxa3d2fNMRGHRUK0fME5/U09llYICgHD7C3DmemMj/94bHz0vnr4SMHlapko4ABim0n957M4jmIogrPCxw5WS/QqB42lyynswIYFFCJmCa2pRQXX5IGMCpeEezBhz+WCUjwgDnMcVSwlDCwM=,iv:ifv7wvTakpv8/4kd/OROxhH7VJBjraGM4WkGUKRTZ9A=,tag:po+xKPedgy/rqQMckdtToA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
