cloudflare:
  api_token: ENC[AES256_GCM,data:RKuY0S/80jg85aTQRr0ANcrqAIRHg47YDgwqw8uGkKWGtIXgEnt90wJBu0w1iYAhLO0FE7Q=,iv:gG+qwXJj1tSoH3Nop1knYh+7R/hNvIrSLalXnWB+adA=,tag:RRDSecPRKu+uK76GqXw2Lw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUjRwRzJwNm1PSC96YnA3
        bGFhZlVYeEh4TFJEbTh2Qk5DR0NHSWJubkZNClFpbkM2S05XeTA3Y3RZQnl0bG1P
        YldoYTJZSWlTM1BDRHNUZ2FrZGN6c1kKLS0tIFl1Z2p1YkRyWEp5MGRDdzhPUWlZ
        a3lwQ1JpdWh1MEFTZExIeFlMUW42VjgKBM3KIRjjqSmnHFcOjLQF5Yb6z+k2nNpZ
        KyMWBmf0aO9dp5AlpJ6E90Jya3VB1swXloDhS90DMuETf0KfNKq+4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-08-06T13:07:43Z"
  mac: ENC[AES256_GCM,data:WzJyz4YNOQQ+rYyKexS8KhmtwIQldcypVLBXPs3w7MvuWPlVbuJfJN6aacINFD6mGm+aBgZq4BKPPobidK//QPZKU9YL7mY+4GO2Pb9dzbIm/eI7PtZEyJOTpDjnGSoRENPMtRPoXZG6MonfjheHEisLPE/PgqxgGPS1e9cN7uc=,iv:SBCcjrEUIXaUCzYVH+uShRa9Rf4kw5I8NPYmpFF0Mi8=,tag:D52Mym0wr+ym05sB82hZCg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
