seaweedfs_s3_access_key: ENC[AES256_GCM,data:AN1yi7IFS1NdfhIyo3KHkWQBNeuJKuMxzNaJqCke4qU=,iv:iBDHY3aUwXwn1zvLJXZ3SUotkHxxQvpdjCa6AQjTj8U=,tag:A8B/7hT80IDlB6F38uoW2g==,type:str]
seaweedfs_s3_secret_key: ENC[AES256_GCM,data:74jokUWr1S/wKv9ZKw+IqIConErHevteiD5OwEnhEfj7F0eHwopIUA4juxaK2tPlVIvFkBpU/zYSbwsfXX1rMw==,iv:3T7sKvmmQl3sww9cvcirvKiFTZ10/s4cA4QUxfXRQQo=,tag:Zl8I9+OKgVpk+IXkuZX9nA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWDlvUlJIWXh1R2k4Wm12
        VzFmcDFFNkMwOVdSWVpJSmw3SlJ3Nll6Q3pBCjFDNmFqVDFIeDg5YzZUdWhydWtN
        YldtUkJtOHNDRThFb3AvY2Y5azlnTDQKLS0tIGRac1NJK1BRNy9IbzJSUWVOTEdu
        MGI2bWNTczAwTERRN2lrais3bTJyKzgKiHSdHIbq78eUitzAZVU2ffrzon0a9QjP
        TQYuLGr8VdphYcTLwVqARIavcYAU+cIUgUxZeIRZUIKfYAbFyPR1EQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-09-12T10:23:46Z"
  mac: ENC[AES256_GCM,data:Y84em9wXe0imrg7tpQs5vg7iiVOYQPS0pyvbXGePBmAYrNXlu2eYzFhDsgHo7OmuSKWDPglVP/jbbu4Njq8zngvPG4LHNFwgxAIBgZ0hSWWtYxHoPB5E4njOUYOg0uj0AEj1m779B4E3aqrOP9SkPSrKbjGe2fdPL0Kb1HHMDy4=,iv:CM5HPEKvDjIKiaId3koZ/Gbpf5TeZFjEqsDcF58o1lc=,tag:D96E76Gt4JPxV6n9+9nxCQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
