seaweedfs_s3_access_key: ENC[AES256_GCM,data:cAZZWrghPXmQZG2rZXHDzXsPZbaEOJAFpllpyAFtn0U=,iv:5kxFUXRv6NO7ucbMXbAVdt5Z7Do02Isyj1DViP1dERo=,tag:oGCQdfm389mmuSC/dZFtFQ==,type:str]
seaweedfs_s3_secret_key: ENC[AES256_GCM,data:pErz103LltWJa7j2NPRfs4V9WDBdpbgvQXd53lLt6Ysfiuz3YxG5EEezAwTz2UqTsYA+VSGfAlLbYumDcExe6A==,iv:mbYb//xfI7ZQ8qCrs9i7JeU3xaLiuzxR6oUWSCKwcDs=,tag:FX7cR/2mAqiPTcimu2rcDg==,type:str]
seaweedfs_gitea_access_key: ENC[AES256_GCM,data:sxTZ4aGLk6g5SnHrEFLR8tAUDV4hheqwqg==,iv:1axrwskowTMchbqg4PDuiPRgV6ZIEyhLZe82d04Uwt8=,tag:b08fWV+XyMI98MpbXEdy6A==,type:str]
seaweedfs_gitea_secret_key: ENC[AES256_GCM,data:oyKn4/fPLUueuVGtbqRlODWWBMky9uuU3QcJrZ66HA==,iv:tWsi/wJ0g/K4UwR6ospQMSqf3q3vLXxmd2LRhqhkM5c=,tag:6gLMpc9RlxYwokF0M8E2rA==,type:str]
seaweedfs_harbor_access_key: ENC[AES256_GCM,data:rDbh+pV+tqqepZJuiSzdxRCgZ5rqcowyM9Nb6twHDoM=,iv:xat47D5OTwIF3wAJb516exQrtWh0tj9lUvcakQuN//E=,tag:s88codeWGzgG5GKZrfBlcg==,type:str]
seaweedfs_harbor_secret_key: ENC[AES256_GCM,data:I/+4g7SaC6KORE9shxwlutXZeygVPDV3IBS9lksi3s4TaiZOdEZnJ5Y28gdbL6n/,iv:wI8zJPZibzAb23uK8qeDiAYP29zkY8Ul9VedDwpb3Tc=,tag:7U1MUzIb+qYH4kBP8ybQCQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R21MMk1DUjJybHh0N1V1
        TzVmOHpsZjZ3N2NRcUF0NlNZaUlWT3dmYTFzCmtGNDZUQzFJelRXSTF5OXRPekpj
        M0IvRzBxUmZoRG01KzBTdGFnT2lvUU0KLS0tIFRhNlRjZDNVNUlQRmZUaWJpMlZ6
        N3k0bkszVmRqb2xWMWc2VlFoS1ZSSjQKJOUnT/ULvgkdQ6Om9DKUDLPmwQ1IgDbZ
        gynolvxslurMKBEC6YFdP7NWHKA4xr0zh6YQfKOJlq+H/Ix8DCnaiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-09-12T12:39:39Z"
  mac: ENC[AES256_GCM,data:GFI8ef4QFx3NssKEIsOpRuMAeZndGN962ackYPttTX1OR2IiW+/Qh30yWo9nWpqcPkmm1aXSBadDRbgKFF/ukt8el5BsNF4417lzNQccBLCUK7zlClDE6xJ9K7LUvM/z7akH5QZUXcHtKpNTqp/H+UIthZVj0TNJhPHHwd1UVvw=,iv:jSFACDRmllV0bv0YXJWRrmbPT5+MTCphukuj9AeWwIg=,tag:Lk1gNGYCVKvpc3AHLZ/ZNQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
