seaweedfs_s3_access_key: ENC[AES256_GCM,data:cAZZWrghPXmQZG2rZXHDzXsPZbaEOJAFpllpyAFtn0U=,iv:5kxFUXRv6NO7ucbMXbAVdt5Z7Do02Isyj1DViP1dERo=,tag:oGCQdfm389mmuSC/dZFtFQ==,type:str]
seaweedfs_s3_secret_key: ENC[AES256_GCM,data:pErz103LltWJa7j2NPRfs4V9WDBdpbgvQXd53lLt6Ysfiuz3YxG5EEezAwTz2UqTsYA+VSGfAlLbYumDcExe6A==,iv:mbYb//xfI7ZQ8qCrs9i7JeU3xaLiuzxR6oUWSCKwcDs=,tag:FX7cR/2mAqiPTcimu2rcDg==,type:str]
seaweedfs_gitea_access_key: ENC[AES256_GCM,data:sxTZ4aGLk6g5SnHrEFLR8tAUDV4hheqwqg==,iv:1axrwskowTMchbqg4PDuiPRgV6ZIEyhLZe82d04Uwt8=,tag:b08fWV+XyMI98MpbXEdy6A==,type:str]
seaweedfs_gitea_secret_key: ENC[AES256_GCM,data:oyKn4/fPLUueuVGtbqRlODWWBMky9uuU3QcJrZ66HA==,iv:tWsi/wJ0g/K4UwR6ospQMSqf3q3vLXxmd2LRhqhkM5c=,tag:6gLMpc9RlxYwokF0M8E2rA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R21MMk1DUjJybHh0N1V1
        TzVmOHpsZjZ3N2NRcUF0NlNZaUlWT3dmYTFzCmtGNDZUQzFJelRXSTF5OXRPekpj
        M0IvRzBxUmZoRG01KzBTdGFnT2lvUU0KLS0tIFRhNlRjZDNVNUlQRmZUaWJpMlZ6
        N3k0bkszVmRqb2xWMWc2VlFoS1ZSSjQKJOUnT/ULvgkdQ6Om9DKUDLPmwQ1IgDbZ
        gynolvxslurMKBEC6YFdP7NWHKA4xr0zh6YQfKOJlq+H/Ix8DCnaiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-09-12T11:31:50Z"
  mac: ENC[AES256_GCM,data:qRvE08/zmm6B9QGtuRe4+WFwNIz3Jli/CrxI8Jk3tZO4XDzKdigaqeDeb5L5grEVohg6BhmJiuIhb27SEyh7KK+JUKRpmhPMTPGviKKbkSNhaKQvXQ/gisatW1zaQD0aijZUl889fROtY0qyRAQP2i0rkaYbkCq6qSneDBmTOwY=,iv:hNZJY1FSCLl/zf3SUy+M6JLFS+vsOSkA0LlI3+gGk4s=,tag:HxKQq3gDT3+NhBO/F+Z02g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
