---
seaweedfs_domain: s3.lab.canhdinh.com
seaweedfs_gitea_bucket: homelab-gitea
lego_domain_names:
  - s3.lab.canhdinh.com
lego_certificate_name: s3
lego_hooks:
  deploy:
    script: "{{ lookup('ansible.builtin.template', playbook_dir ~ '/roles/seaweedfs/templates/lego-deploy-hook.sh.j2') }}"
