---
seaweedfs_domain: s3.lab.canhdinh.com
seaweedfs_gitea_bucket: homelab-gitea
seaweedfs_harbor_bucket: homelab-harbor
seaweedfs_ui_endpoints:
  - { domain: seaweedfs-master.lab.canhdinh.com, port: 9333 }
  - { domain: seaweedfs-filer.lab.canhdinh.com, port: 8888 }
  - { domain: seaweedfs-volume.lab.canhdinh.com, port: 8080 }
lego_domain_names:
  - s3.lab.canhdinh.com
  - seaweedfs-master.lab.canhdinh.com
  - seaweedfs-filer.lab.canhdinh.com
  - seaweedfs-volume.lab.canhdinh.com
lego_certificate_name: s3
lego_hooks:
  deploy:
    script: "{{ lookup('ansible.builtin.template', playbook_dir ~ '/roles/seaweedfs/templates/lego-deploy-hook.sh.j2') }}"
