harbor_admin_password: ENC[AES256_GCM,data:YusmEw+xqPrLLOkBLjXDBXf5YgsvNUqm1YX2yKIFLlSdORbwSZbMpNaNBqeJ9+/f,iv:WUImhYWbK8wvSsYLv9z9io+YEOD4/eK4VpCJXlwMDQ4=,tag:/akqmistunJK8aYbRoNxSw==,type:str]
harbor_s3_access_key: ENC[AES256_GCM,data:Bzm780scvTtaIZJoVCgzPorjsM3Y7gOC3szs8i2o9Ok=,iv:oHl9yq8bJsuFPMX3HCRIj8cBp4+UqjIoxpNMGeZ1XJ0=,tag:Lniq6m5v4y8W2LPmyEfV0w==,type:str]
harbor_s3_secret_key: ENC[AES256_GCM,data:jtakK7mxNchp3DYbt360jZcGMWtzYZ9G12aXcPWHFkPELX6XERrdTBCVcWe4pG9O,iv:l6kU9j22Gc6FC8JpifIULTXSpT97Y+FjYMNJxtA7A1U=,tag:jYtlu0k9bsILpWUDjgLYNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMS9ieXVDclpwMEllRzZ4
        enFvWmhPK0hSR3k4Rlczb3A0NUdRZUJwc1hnCm8xQldwNCtXL3ZicWw0dkxYOUNS
        WFpTcVZhaUFiS2ZPZ0d5YTE1Rk9Kck0KLS0tIFFVUTlVQ0dJSXF6Mmw2S2puc3Np
        S3Z5VEJyM1FNNTNIeDZKU25YMmxwRmMKlxfZe9UypwULxobNdbMrLqGU3nBsZJwD
        DeXvKcci1bjQDTwW414eiCrCO8kuzMg2Qs6LI0htfF7saNCRnk/uCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-09-12T12:39:39Z"
  mac: ENC[AES256_GCM,data:T7oHHq6i86e0r9Dit9cPdWbSefl5/UV1B1Vbl3ooU3BzZYn2BMSl5FMCZLzEmctL2RWRlcYI7WDq4aiMBrRKzTf5gLWZo5qH9RlskfTcaHHq8L+tAtvvUC7cwI4tW7lrnTAue3zyBxsGTg2tgs+EjpOZy4h4a6DBrI0DHc0ijUE=,iv:qve7yoFN9Br9bE8s+xlYoTAVD0MU4/D9QaDT+GwAs48=,tag:V+o4I5jvwzJ+VqG9NGOiKg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
