cloudflare_api_token: ENC[AES256_GCM,data:u1bx0I6R/O73askyc2BxkM32VSNt9PukEuHePfpksWB+xWia9Xzvd6m4PTq6Rm2D/WD1DHk=,iv:uPoSoHhiUOSGS/WwGn1Polyz5OmOjUkAnmNJqtuFgPY=,tag:pDfs6u9cropdrV5yP0nsYA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWmtvaWpOZDlKdTliZEVC
        blBrN2dsNVl4ZkovN0Y0Y2JtaVBTUmttc2dnCmtSY2N4R1FaWjhHTXlHWG41clR4
        cXlqVGRFc01PS1loV2krN2ZuUnEzalEKLS0tIGdybFkyV1pxd3pxYk82MXgwa2Nz
        VFVwcFp6M2ViUG5zdWRDTW9nTDVOVHcK9ARmSIoAghSXOVK5ln2SZkHAzf9HIBbg
        dhb/ntCRIpgXace9B0Y/KxjdtcIg8fuy21hW5rFw12ffb80mmrYC9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-08-14T11:56:28Z"
  mac: ENC[AES256_GCM,data:YrKA5UnQuOvHa5biF7EEBKbyeW7ZZYkBqSvG5APTqCPZKsS0I9j0nTuw4KywhiBY2v2eKnUDen/QTu8v96fgHpX0NBiP+7iT254u5jcv5ggBJTdbbdN+gdsXjdvGR6i6yGP71ARO0+BmQujgMZhDDd98PMmthWVa8jMxyHCSIi8=,iv:dwgQo2b5iqd/2pzHDRk7bqjb4aG+tUaqxOUJSZ9FiSo=,tag:bq7Bm20HEalk/NS6Mvr3Gg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
