harbor_database_password: ENC[AES256_GCM,data:vQnqGN594IPfdhs5FtmQz2V1ARLlzhhK6ksgDumvbJHgpceAxwPkPDv6MOJ+v92Y,iv:iLjCVYfCjG5DZdBewQck2SzfxadShVS8iBTBRb6bApM=,tag:Fu0dk3F1WfQkW9MWK6LYTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMGZ0WlRvbHhocUZadjUy
        Z2FmY1F4NTlzd0hQRmgyVU9nOXVXRVlYYVIwCko5ajVDYTAzeTd4STk0ZkFPdC9P
        c2RBcURYeFQ2UkJFbWlmZlRUL0R4eUUKLS0tIEVGQ0tkMEdYTUgrekMwSDJLTjRN
        MzJkVlhyalZIalY4dTFuQjRZUzh1b3MKbpOMmNpcL1QqF0qJlUUDhNHJuiMeXfI8
        ajyHevgILz6jNAnxQMVWp1If0y3/Yjen9U3O34hcgQyXTjLlDoev+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-09-12T12:39:39Z"
  mac: ENC[AES256_GCM,data:f1TAyPZjJnvMPFSJ1nbPdeTIIqjU5KDY+NtVwKOBUd8BOZexQIvGmnKae5935NRZRiLFUXgqNB6hYB1KLkHWfbSKHWZ5oSOPGi+Y/pYy90N7r75VEb81jKX2tSWt5YwDEpLQlAcl3p6YytXCAnCXF4Fno4YKa1j40bfacuEUtGk=,iv:qrlA+ADr3wbEasi7dGltPRwtZ7lGy9YgwaonzXR8GCA=,tag:KMNVCcVx4PgNcsjREcmS/g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
