---
- name: Import validation tasks
  ansible.builtin.import_tasks: validate.yaml

- name: Import installation tasks
  ansible.builtin.import_tasks: install.yaml

- name: Import backup tasks
  ansible.builtin.import_tasks: backup.yaml

- name: Import release tasks
  ansible.builtin.import_tasks: release.yaml

- name: Import runtime tasks
  ansible.builtin.import_tasks: runtime.yaml
