gitea_database_password: ENC[AES256_GCM,data:1dP1oKnWWcF8EU5DT3XYSkHLflcSYpJqtkUnOR4WqIoCWDlRz7If1CFe6YyNTnbC0hm5C0T69HGmE31uC6JQ9A==,iv:KARF17CxTviaUm3fIj0h0AUn9IJKfPv+9J/RTudhkqc=,tag:uG+8l4TB+p/NPnx3qLZktQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT0cxdHl2TWZJdzZybjg4
        WUNjOEEvalk1L0lYanJubVh2T3NFRVV5cURZCkRuNXhyS0R0VGNRQXA4TFpORDVq
        aktwcnRCQjkxVzdjNlpJWXJGVnh5dm8KLS0tIDkvdmRLNnQ0NnlwUkE4SG9iY3Nm
        dEltQzRLTnZKUnRDenRzMVhmb1JkQWMK/7e3DTqnjOKp1Op38FiWx4dYg8Z2wFTE
        +gSm0L3g9qg2+g7q22VSJ6w7yOUaCERjfPVDBrxmbWOV51S63+vfoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-08-14T11:56:28Z"
  mac: ENC[AES256_GCM,data:Ahq7JK6Ihc66yUl8Ta1Bk3P9s9wRtIfHrga/FJeeIGb4rDoc50Iy/nfy41ebmIRdNpRqCjvwTPffvkwzKCup1fHAT5MSMhsJFR4obks59pA/LaoyAW4+D9W+cOG9TVbvLJkKosn7GTUVoFSPXWaa9KgqEmevElTn429G+fMJbJU=,iv:HjIxlO40Le6MKOz3hjGuZZLSRKCXy3kj4q6tNXdiVsc=,tag:DWB1Hitjntoe1nxVVOrKew==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
