---
- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart SeaweedFS
  ansible.builtin.systemd_service:
    name: seaweedfs.service
    state: restarted

- name: Validate Nginx configuration
  ansible.builtin.command:
    cmd: /usr/sbin/nginx -t
  changed_when: false
  listen: Reload Nginx

- name: Reload Nginx service
  ansible.builtin.systemd_service:
    name: nginx.service
    state: reloaded
  listen: Reload Nginx
