- name: Get TLS certificate for Technitium DNS server using lego ACME client
  hosts: dns
  become: true
  vars:
    lego_domain_names:
      - dns.lab.canhdinh.com
    lego_certificate_name: dns
    lego_pfx:
      password: "{{ technitium_pfx_password }}"
      format: SHA256
    lego_hooks:
      deploy:
        script: |
          #!/bin/sh
          set -eu

          install -o dns-server -g dns-server -m 0600 \
            /var/lib/lego/certificates/dns.pfx /etc/dns/dns.pfx
          systemctl restart dns.service

  roles:
    - lego
