---
harbor_version: "2.15.2"
harbor_installer_checksum: sha256:88f6a7436b31890e8e472972a7433d36b7d6a36de9adeb86337fdc9fe7fb5fa3
harbor_installer_url: >-
  https://github.com/goharbor/harbor/releases/download/v{{ harbor_version }}/harbor-online-installer-v{{ harbor_version }}.tgz
harbor_install_directory: /opt/harbor
harbor_data_directory: /var/lib/harbor
harbor_tls_directory: /etc/harbor/tls
harbor_tls_cert_path: /etc/harbor/tls/server.crt
harbor_tls_key_path: /etc/harbor/tls/server.key
harbor_https_port: 443
