---
harbor_version: "2.15.3"
harbor_installer_checksum: sha256:b44dad3d0f0ca1426f82d1db3597bc4b82af4c7ec58e3dd96703eeedee7e7a5b
harbor_installer_url: >-
  https://github.com/goharbor/harbor/releases/download/v{{ harbor_version }}/harbor-online-installer-v{{ harbor_version }}.tgz
harbor_install_directory: /opt/harbor
harbor_data_directory: /var/lib/harbor
harbor_tls_directory: /etc/harbor/tls
harbor_tls_cert_path: /etc/harbor/tls/server.crt
harbor_tls_key_path: /etc/harbor/tls/server.key
harbor_https_port: 443
