---
gitea_runner_version: "4.0.0"
gitea_runner_checksum: sha256:02a3f52a9c8f3bb2d60f12696afea95ab980cbe1a60ec6eaa575749836c85216
gitea_runner_download_url: >-
  https://dl.gitea.com/gitea-runner/{{ gitea_runner_version }}/gitea-runner-{{ gitea_runner_version }}-linux-amd64
gitea_runner_user: gitea-runner
gitea_runner_group: gitea-runner
gitea_runner_home: /var/lib/gitea-runner
gitea_runner_config_directory: /etc/gitea-runner
gitea_runner_config_path: /etc/gitea-runner/config.yaml
gitea_runner_binary_path: /usr/local/bin/gitea-runner
gitea_runner_registration_path: /var/lib/gitea-runner/.runner
gitea_runner_instance_url: https://gitea.lab.canhdinh.com/
gitea_runner_name: gitea-runner
gitea_runner_labels:
  - debian-amd64:host
gitea_runner_node_major: 24
gitea_runner_node_version: "24.21.0"
gitea_runner_nodesource_key_url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
gitea_runner_nodesource_key_fingerprint: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4
gitea_runner_docker_device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_incus_data
gitea_runner_docker_mount: /var/lib/docker
gitea_runner_packages:
  - bash
  - build-essential
  - ca-certificates
  - curl
  - git
  - git-lfs
  - gnupg
  - jq
  - openssh-client
  - rsync
  - tar
  - unzip
  - wget
  - xz-utils
  - zip
