gitea_s3_access_key: ENC[AES256_GCM,data:3cs3wiqDWzVE+h4y+peqksxAsJF+bgsl8Q==,iv:kwuanAWFUELgNhPvweqsN8H/v6Tl0dlnAWYSyNZd4M8=,tag:onf5VBZAvsO0zbGGhBiiPA==,type:str]
gitea_s3_secret_key: ENC[AES256_GCM,data:a1MDB1k4oUH9N+tn1ejG7TSd0ui7vXitrdp99ydXsw==,iv:8ejVk4QuRJ68Jp18gHU7j3ZuoKLAl07sAcNqV5K3nPA=,tag:zmHhb15CqzFgibeH1YrsWA==,type:str]
gitea_smtp_password: ENC[AES256_GCM,data:QgzXAkP281p9HoQGN4plhXi62n6+XR81kEc/GnLXgqfJpWDqf1D4wVXMM+PCPBXNLHQJ4qtXis92wMU8sNQVLPb6dBnYb1YgLqBn7gUL+F6KIHGeg8MA+lFL,iv:/To8ib91EMemadh2mVqyZ9ofMSVM5GQSSMOVgqfLmlQ=,tag:bQgjRLbJUOfFq2wPSl1+Mw==,type:str]
gitea_secret_key: ENC[AES256_GCM,data:VEh9oiXmrCJRGXEvOgIC6RaiOmBeFIqCw2hTwqTI46KcK57nJkILmuxVpKWDgfXq/b836TUJRBT/1nRn29gUuw==,iv:We4ZGnYxLAq4ncWHfZm+MB+Z5PC+YWywICaHSyUmWhw=,tag:68HtrJtSVYKEBSIs1+/fVw==,type:str]
gitea_internal_token: ENC[AES256_GCM,data:EKGL0IOFjYe71eBZoMw5J5wnhOOTzJX2VmWsbPfTh1Uggx6Jb3TN3eGwuazPYi/lhbNURbrlwHcSWmuIgBbB3g==,iv:p4YHpoCJtQiEJzh6RTilh8UwXR6XV1w/tW81fHf39wk=,tag:dqDI8oX8qc0b+XH2eKrfwA==,type:str]
gitea_lfs_jwt_secret: ENC[AES256_GCM,data:SNiRzVFb06orQTVm6E72oNuIc4k+WVPEI8ZhzcD69j1zSKxh2ZA6kYUHQg==,iv:ND47TEOagocPwwP7FgryHx97VkFl6pxYuPzfZ9mGVjM=,tag:qNqcfmRtnifNYlABx4qCxA==,type:str]
gitea_admin_password: ENC[AES256_GCM,data:B2fCE1C56qeO+img/XGtq0lshgI3zR9WtCXnvaYDm0yWSD2SpmzSa777OmT5Kx5G1VDzMvnTyacC6rfFcjYYVw==,iv:v9XC9CwDrWo/H3/aYXZeGHP7kwOgwoliGPn/A4plHBY=,tag:9aS/39avYtia5LHWMt3OOw==,type:str]
gitea_oauth2_jwt_secret: ENC[AES256_GCM,data:wkN+nacQinpzdNQ53EyEHxkgCWTvkQqwMha3201ed1j5ZF5BQ5GXH+KFlg==,iv:oNsFHJsjnLFV32Q2MTf3E8w5NtraSv9BfH8YGvdz6lc=,tag:4b4MHJCsMRbonrxYazR5Uw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU1VlWUJ0cGxmWDZLdU0v
        N1ZHVXVGelNKc3R5WkpFSU5vRWhtNUpKaGpFCmh3b3pPUlB5Rng0ZVlwaVZ3N0E2
        Mm5zQmhwNnpXandwU1dRZVdPVlhBd1UKLS0tIG5WUkh2T1BTaEhBcE5NSGJ0V2lp
        NnN4Q3E4akE0TytTT2pSNEJlKzlzSzAKLxADOj43owTWxdXTKsBdjoFhTpYYZi+v
        aXg5JZc8XHO0f5fVai8kBFEMp91RS2UcynY/ZA5Z7wnp+3XKM5i1Aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age134tr568at5vanpnt2f29925cxflwtzy2cmxrvcwt2e9tupm48vusvrl2t0
  lastmodified: "2026-08-14T11:56:28Z"
  mac: ENC[AES256_GCM,data:ysImcThJgI/cbrbq4xtnehMqt8eR+oWuWEzHEzYY8QoVbOx2JJwbjnCbgeLdVrV7u2J/nZU3sXXIeizysWaeBFh4plG/be8DKGFHuRrpuYuaoqhgPVHgYgYr3S9gBe5JdAMrQqUbVPn9/vnss+/ajK4tu5zzypuEdkxcCATyFzc=,iv:EPV9azVTFTyVVD098FMxxdxoEqCurTBY5Bzf7Udn7Ag=,tag:FEn2GnfRJRyHCMscriK58Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
